Ukraine_map/Ukraine_map/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('places.urls')),
]

Ukraine_map/places/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ua_map),
    path('create/', views.create),
    path('delete/<int:id>/', views.delete),
    path('edit/<int:id>/', views.edit),
    path('add/', views.add),
]

Ukraine_map/places/models.py
from django.db import models

# Create your models here.
class Place(models.Model):
    name = models.CharField(max_length=250)
    latitude = models.FloatField()
    longitude = models.FloatField()
    location = models.CharField(max_length=100, default='not indicated', null=True)
    
    def __str__(self):
        return self.name

Ukraine_map/places/forms.py
from django import forms
from places.models import Place

class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter name"}),
            "latitude": forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter latitude"}),
            "longitude": forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter longitude"}),
            "location": forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter location"}),
        }

Ukraine_map/places/views.py
from places.forms import PlaceForm
from places.models import Place
from django.shortcuts import get_object_or_404, redirect, render

# Create your views here.
def ua_map(request):
    places = Place.objects.all()
    return render(request, 'index.html', {'places': places})

def create(request):
    if request.method == "POST":
        form = PlaceForm(request.POST)
        if form.is_valid():
            place = form.save(commit=False)
            place.save()
            return redirect('/')  
    else:
        form = PlaceForm()
        return render(request, 'create.html', {'form': form})
    
    return render(request, 'create.html', {'form': form})

def delete(request, id):
    place = get_object_or_404(Place, id=id)
    place.delete()
    return redirect('/')

def edit(request, id):
    place = get_object_or_404(Place, id=id)
    if request.method == "POST":
        form = PlaceForm(request.POST, instance=place)
        if form.is_valid():
            place = form.save(commit=False)
            place.save()
            return redirect('/')  
    else:
        form = PlaceForm(instance=place)
        return render(request, 'edit.html', {'form': form, 'place': place})
    
def add(request):
    if request.method == "POST":
        form = PlaceForm(request.POST)
        if form.is_valid():
            place = form.save(commit=False)
            place.save()
            return redirect('/')  
    else:
        lat = request.GET.get('lat', '')  
        lng = request.GET.get('lng', '')

        form = PlaceForm(initial={'latitude': lat, 'longitude': lng}) 

    return render(request, 'add.html', {'form': form, 'lat': lat, 'lng': lng})

Ukraine_map/places/templates/add.html
{% extends 'create.html' %} 

{% block content %}
<div class="container mt-5">
    <div style="display: flex; align-items: center; margin-bottom: 20px">
        <a class="btn btn-outline-dark" href="/" style="margin-right: 10px;">
            <i class="bi bi-box-arrow-left"></i>
        </a>
        <h1 style="margin: 0;">Add Place</h1>
    </div>

    <form method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="id_name" class="form-label">Name</label>
            {{ form.name }}
        </div>

        <div class="row">
            <div class="col">
                <label for="id_latitude" class="form-label">Latitude</label>
                <input type="text" id="id_latitude" name="latitude" class="form-control" 
                       value="{{ form.latitude.value|default:lat }}" readonly>
            </div>
            <div class="col">
                <label for="id_longitude" class="form-label">Longitude</label>
                <input type="text" id="id_longitude" name="longitude" class="form-control" 
                       value="{{ form.longitude.value|default:lng }}" readonly>
            </div>
        </div>

        <div class="mb-3">
            <label for="id_location" class="form-label">Location</label>
            {{ form.location }}
        </div>

        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button type="submit" class="btn btn-outline-success">Add</button>
        </div>
    </form>
</div>

{% endblock %}

Ukraine_map/places/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Place</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body>
    {%block content%}
    <div class="container mt-5">

        <div style="display: flex; align-items: center; margin-bottom: 20px">
            <a class="btn btn-outline-dark" href="/" style="margin-right: 10px;">
               <i class="bi bi-box-arrow-left"></i>
            </a>
            <h1 style="margin: 0;">Provide valid information</h1>
        </div>

        <form method="post">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_name" class="form-label">Name</label>
                {{ form.name }}
            </div>

            <div class="row">
                <div class="col">
                    <label for="id_latitude" class="form-label">Latitude</label>
                    {{ form.latitude }}
                </div>
                <div class="col">
                    <label for="id_longitude" class="form-label">Longitude</label>
                    {{ form.longitude }}
                </div>
            </div>

            <div class="mb-3">
                <label for="id_location" class="form-label">Location</label>
                {{ form.location }}
            </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-outline-success">Submit</button>
            </div>
        </form>
    </div>
    {%endblock%}
</body>
</html>

Ukraine_map/places/templates/edit.html
{% extends 'create.html' %} 

{% block content %}
    <div class="container mt-5">

        <div style="display: flex; align-items: center; margin-bottom: 20px">
            <a class="btn btn-outline-dark" href="/" style="margin-right: 10px;">
               <i class="bi bi-box-arrow-left"></i>
            </a>
            <h1 style="margin: 0;">Provide valid information</h1>
        </div>
        
        <form method="post">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_name" class="form-label">Name</label>
                {{ form.name }}
            </div>

            <div class="row">
                <div class="col">
                    <label for="id_latitude" class="form-label">Latitude</label>
                    {{ form.latitude }}
                </div>
                <div class="col">
                    <label for="id_longitude" class="form-label">Longitude</label>
                    {{ form.longitude }}
                </div>
            </div>

            <div class="mb-3">
                <label for="id_location" class="form-label">Location</label>
                {{ form.location }}
            </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-outline-success">Edit</button>
                <a class="btn btn-outline-danger" href="/delete/{{ place.id }}">Delete</a>  
            </div>
        </form>
        
    </div>
{% endblock %}

Ukraine_map/places/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Full Screen Map</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        #map {
            height: 100%;
            width: 100%;
        }
        .card .card-link {
            color: black !important; 
        }
    </style>
</head>
<body>


    <div class="floating-btn">
        <a type="button" class="btn btn-outline-secondary" href="create/">
            <i class="bi bi-plus-circle"></i>
        </a>
    </div>    


    <div id="map"></div>

    {% if places|length > 0 %}
        <script>
            var map = L.map('map').setView([48.3794, 31.1656], 6);
        
            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            }).addTo(map);

            map.on('click', function(e) {
                var lat = e.latlng.lat;
                var lng = e.latlng.lng;
                console.log("Clicked on map at:", lat, lng);
                
                window.location.href = `/add/?lat=${lat}&lng=${lng}`;
            });

        </script>

        {% for place in places %}
        <script>
            var marker = L.marker([{{ place.latitude }}, {{ place.longitude }}]).addTo(map);
            
            marker.bindPopup("<b>{{ place.name }}</b><br>{{ place.location }}<br>");
            
            marker.on('mouseover', function() {
                this.openPopup();  
            });

            marker.on('mouseout', function() {
                this.closePopup(); 
            });

            marker.on('click', function() {
                setTimeout(function() {
                    window.location.href = `/edit/{{ place.id }}/`;
                }, 100);
            });

        </script>
        {% endfor %}


        {% else %}
            document.write('<p>No places available</p>');

    {% endif %}
        
    
</body>
</html>